### ISSUE TITLE
Requiring trusted_ca::ca source use certfile_suffix seems unnecessary?

### ISSUE THREAD

**Issue by optiz0r** [voxpupuli/puppet-trusted_ca#38]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.23
- Ruby: N/A
- Distribution: CentOS
- Module version: 4.0

## How to reproduce (e.g Puppet code you use)

```puppet
trusted_ca::ca { 'puppet':
  source => '/etc/puppetlabs/puppet/ssl/certs/ca.pem'
```

## What are you seeing

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, [Trusted_ca::Ca::puppet]: source must be a PEM encoded file with the crt extension (file: /etc/puppetlabs/code/environments/production/modules/trusted_ca/manifests/ca.pp, line: 62, column: 7) (file: /etc/puppetlabs/code/environments/production/site-modules/profile/manifests/base.pp, line: 8) on node example.com
```

## What behaviour did you expect instead

The source file should be accepted, regardless of what file extension it uses, since it will be copied to the install_path with a chosen filename anyway. I don't see a reason why this is considered unacceptable.

https://github.com/voxpupuli/puppet-trusted_ca/blob/master/manifests/ca.pp#L61

```puppet
    if $source !~ Pattern["\\.${certfile_suffix}$"] {
      fail("[Trusted_ca::Ca::${name}]: source must be a PEM encoded file with the ${certfile_suffix} extension")
    }
```

This condition and the corresponding `fail()` could be dropped entirely, I think?

The workaround is to create a symlink to the real target with the desired file extension, and use that for `trusted_ca::ca`, which works, but should not be necessary.

**Comment by ekohl** [comment]
I did a bit of digging and it looks like it was originally introduced as part of d2d3ee6a647c6526686e4f96811d40e6e232a34e but I think you're right. I fail to see how the **source** needs to have a certain file suffix. You really want it to be PEM encoded but the file suffix doesn't guarantee that.

> This condition and the corresponding `fail()` could be dropped entirely, I think?

This sounds ok to me.
